### ISSUE TITLE
Build issues with Xamarin.Forms

### ISSUE THREAD

**Issue by michaelmairegger** [efcore/EFCore.SqlServer.HierarchyId#10]
Hi,
thanks for the great library that works like a sharm on WPF. But if I want to use the a library that is used on WPF and Xamarin.Forms togethen then i get the following exception:

> ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): Error XALNK7000: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Void Microsoft.SqlServer.Server.SqlUserDefinedTypeAttribute::.ctor(Microsoft.SqlServer.Server.Format)' (defined in assembly 'Microsoft.SqlServer.Types, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null') with scope 'System.Data.SqlClient, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Microsoft.SqlServer.Server.SqlUserDefinedTypeAttribute::.ctor(Microsoft.SqlServer.Server.Format)

Since _EntityFrameworkCore.SqlServer.HierarchyId.Abstractions_ reference _Microsoft.SqlServer.Types_ only on _.NETFramework 4.6.1_ is seems that on Xamarin the wrong dll is linked.

```
<PropertyGroup>
  <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
</PropertyGroup>

<ItemGroup>
  <PackageReference Include="EntityFrameworkCore.SqlServer.HierarchyId" Version="1.0.0" />
</ItemGroup>
```

The error occurs only when building with AzureDevops. Locally there is no issue.

**Comment by bricelam** [comment]
This looks like an issue for (or maybe just a limitation of) [dotMorten/Microsoft.SqlServer.Types](https://github.com/dotMorten/Microsoft.SqlServer.Types).
