### ISSUE TITLE
Use Microsoft.SqlServer.Types

### ISSUE THREAD

**Issue by bricelam** [efcore/EFCore.SqlServer.HierarchyId#113]
It looks like the next version of [Microsoft.SqlServer.Types](https://www.nuget.org/packages/Microsoft.SqlServer.Types) will finally support modern .NET. We should switch to that when it's released.

**Comment by bricelam** [comment]
P.S. I tested locally with version 160.900.6-rc0 and it all worked.

**Comment by bricelam** [comment]
Then again, maybe we should just do https://github.com/dotnet/efcore/issues/365 instead.

**Comment by Ogglas** [comment]
@bricelam I vote for doing https://github.com/dotnet/efcore/issues/365 🙂

**Comment by NKnusperer** [comment]
Any update on this?  Looks like xplat `Microsoft.SqlServer.Types` is RTM now.

**Comment by bricelam** [comment]
The plan is to move this project into the `dotnet/efcore` repo for 8.0 and update it to use the official types package as part of that.
