### ISSUE TITLE
Security vulnerability:  https://github.com/advisories/GHSA-8g2p-5pqh-5jmc

### ISSUE THREAD

**Issue by iduras3** [efcore/EFCore.SqlServer.HierarchyId#115]
The [Microsoft.SqlServer.Types](https://github.com/dotMorten/Microsoft.SqlServer.Types) use a package with a security vulnerability. A Bug Report was already done for their package https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/80.

**Comment by bricelam** [comment]
Fixing this is outside the scope of this project. We'll update to the latest patched versions of our direct dependencies before shipping, but that's it. Anything beyond that is the responsibility of the user.
