### ISSUE TITLE
The project is not compatible with the new version of EF Core 7

### ISSUE THREAD

**Issue by 7702244** [efcore/EFCore.SqlServer.HierarchyId#116]
A project with this library cannot be run on the new version of EF Core 7. Can you suggest a solution to the problem?

**Comment by ErikEJ** [comment]
Have you tried the 7.0 rc release?

**Comment by 7702244** [comment]
I am working with the stable version 3.0.1 and did not know that a new one was available. When is the stable version 4.0.0 scheduled to be released?

**Comment by ErikEJ** [comment]
Soon. Maybe you can Make it happen faster by trying out the rc release?

**Comment by 7702244** [comment]
I tried version 4.0.0-rc.2 and it works. Thank you! Waiting for the release of the stable version.

**Comment by mehdihaghshenas** [comment]
because this project use https://github.com/dotMorten/Microsoft.SqlServer.Types
and this project use Microsoft.Data.SqlClient 4.00 that has conflict with EF7.0
I fix it and wait to accpet my PR on https://github.com/dotMorten/Microsoft.SqlServer.Types

**Comment by ErikEJ** [comment]
The correct fix is for this library to depend on the latest Microsoft.SqlServer.Types
