### ISSUE TITLE
Contribute to dotnet/efcore

### ISSUE THREAD

**Issue by bricelam** [efcore/EFCore.SqlServer.HierarchyId#119]
Now that an official version of Microsoft.SqlServer.Types is available, the EF Core team is willing to accept this code into the main EF Core repository. To do that, we'll need everyone that contributed to sign the [.NET Foundation CLA](https://cla.dotnetfoundation.org/dotnet/efcore).

Can I get **acknowledgement from everyone** that they are willing to (or already did) sign the CLA? After that, I'll prepare the PR.

Note, the code will continue to be licensed under the MIT--no changes there.

- [x] @ajcvickers
- [x] @aljones (for 61e370ed6d6468ac3b670eacc1f4911fd91e8823, 23edbab2ef9cdc3428fde9ef0c71ac95756949d5, 1a272ad41fbdb1f3e8ffbea8f72f901f7ffff45e, f1ebb4f29ca1c4645c34c4ecbeef6a89aece2e34, 3c6105e69b6b87c2bf33bae8bbe95e34f659d2ad, e683fe011d4e303d60b94846f88ecd1d4f1dff7e & 1347b205aeee718703ac892c9a4216c2341eb756)
- [x] @bricelam
- [x] @cutig3r (for a77a339308d09893820edbac9b2d6e21850980dd & 64fa84e7f7d4c350b0e7fffc25970977dee901e1)
- [x] @huan086 (for 4d6cbc224599a46dd6459ca0b14c7fb8c73b0b93)
- [x] @kmataru (for 0706c523486d254053c24ea32ddf364ea9c8ede9)
- [x] @mehdihaghshenas (for 4fc0b5dc5375cd4094837754a12cb87b1fa44502)
- [x] @vyrotek (for dec60867cafc8d7cd597e23b84a32c2ace7f309f)
- [ ] @yuryjhol (for 0d2cb8763d094ff6bf8e63287408c85311f1bbd3)

And thanks again for everyone's help getting us to this point!

**Comment by cutig3r** [comment]
Signed!

**Comment by vyrotek** [comment]
Done. Excited for this!

**Comment by mehdihaghshenas** [comment]
Thank you
I was very appreciate to hear this news

**Comment by aljones** [comment]
Signed!

**Comment by kmataru** [comment]
🤘 Signed

**Comment by huan086** [comment]
Everyone has signed! Exciting!

**Comment by kmataru** [comment]
@bricelam 
Maybe try reaching out to @yurijhol (Yury Jhol) on LinkedIn, if he hasn't signed this yet.

**Comment by bricelam** [comment]
Yeah, I've tried on a few different channels. But it looks like his contribution was small enough (a one-liner) to not require a CLA.

Things are moving forward nicely in PR https://github.com/dotnet/efcore/pull/30291
