### ISSUE TITLE
In-memory support for EF8?

### ISSUE THREAD

**Issue by bricelam** [efcore/EFCore.SqlServer.HierarchyId#120]
Due to the EF team's [current stance](https://github.com/dotnet/EntityFramework.Docs/blob/35ac32db05d71a574d167f4e077c1adc3f8aad26/entity-framework/core/providers/in-memory/index.md?plain=1#L10-L16) on the in-memory provider, the [EntityFrameworkCore.InMemory.HierarchyId](https://www.nuget.org/packages/EntityFrameworkCore.InMemory.HierarchyId) package will not be contributed as part of #119.

Please let us know here you can't live without it, and we'll consider maintaining a version of it that's compatible with EF8+.

**Comment by bricelam** [comment]
I've updated this repo to work with EF8 GA. Feel free to fork it.

There are still no plans to release it on NuGet.org, but if there's enough interest, I'm open to it.

**Comment by bzbetty** [comment]
I think having it as an option would be nice, while we understand in-memory isn't advised, it really is a handy option to have for fast tests on a cloud build server.

**Comment by canu1337** [comment]
This is a big issue for me. I cannot update to .NET 8 without this.
Thanks for updating the repo, I've forked it and pushed the package on my company private repo.

**Comment by cn-byn** [comment]
This is an issue for us as well. The alternative testing approaches are much more complicated and involved than setting up an in-memory DB.

A new NuGet package release would be much appreciated.

**Comment by bricelam** [comment]
Thank you, everyone, for your feedback! I've published an 8.0.0 version to NuGet.org.

**Comment by saliksaly** [comment]
Thanks, we use this package for automatic tests of out application services.

So now, when the package is still maintained, there maybe should not be this warning in the nuget package:
"This package has been deprecated as it is legacy and is no longer maintained. "
https://www.nuget.org/packages/EntityFrameworkCore.InMemory.HierarchyId

**Comment by bricelam** [comment]
Yes. It is no longer maintained. The 8.0 version was released to help users transition off of it.

**Comment by kinetiq** [comment]
@bricelam Thanks for putting something together for this. I'm having a tough time understanding the fate of this functionality - it sounds like you made an 8.0 version as a temporary measure, and don't intend to support it. Also, as far as I can tell there's no plan for anyone else picking this up... Microsoft seems to be saying they don't intend to carry this forward even though they've absorbed these projects. Is that right?

They also mention "the state of InMemory" in a certasin way as though perhaps InMemory itself is not long for this world. Do you have any other insight into this? InMemory is very useful for testing. We could live without it, but it would be a loss in my opinion. For example I would just delete a bunch of tests, and therefore lose a bunch of test coverage.

**Comment by ErikEJ** [comment]
@kinetiq You should use a real database engine for testing, in particular for a SQL Server only feature like this. See the EF Core testing docs for suggestions and advice.

**Comment by kinetiq** [comment]
@ErikEJ  For what it's worth, I'm not really testing HierarchyId explicitly... It's typically some logic / service that needs testing and the database is either a minor part of the dependency graph or it's needed for retrieving a simple entity. 

InMemory has been reasonable in these cases for loading up simplified entities without needing to worry about keeping a real database instance in parity, maintaining the entire relationship graph for all these tests as the database evolves, etc.

If anything I would love to have *less* of a database. A repository that injects into IDbContext and returns static POCOs we can load up just for that test, etc.

Anyway, these approaches may be  crude, but the reality of small teams is we need to spend our time testing the parts we're most concerned about, not building endless infrastructure... Hopefully I can find an approach that is more of a middle ground. 

I do appreciate the response though since it indicates this is likely a dead end. Big fan of your work around reverse engineering BTW, we use that all the time.

**Comment by ErikEJ** [comment]
It depends as usual, but spinning up TestContainers should not be "building endless infrastructure"

https://testcontainers.com/guides/testing-an-aspnet-core-web-app/

**Comment by bricelam** [comment]
> It sounds like you made an 8.0 version as a temporary measure, and don't intend to support it. Also, as far as I can tell there's no plan for anyone else picking this up... Microsoft seems to be saying they don't intend to carry this forward even though they've absorbed these projects. Is that right?

Correct. I do not intend to create a new version beyond 8.0. If someone from the community is interested in maintaining it, I'm happy to work with them. And yes, the in-memory packages were not absorbed into the efcore codebase.

**Comment by bricelam** [comment]
Note, the 8.0 NuGet package will continue to work in EF9. But you will probably need to add a couple direct/explicit package references to bump up its dependencies' versions.

```xml
<ItemGroup>
  <PackageReference Include="EntityFrameworkCore.InMemory.HierarchyId" Version="8.0.0" />

  <!-- Update dependencies to version 9.0 -->
  <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Abstractions" Version="9.0.0" />
</ItemGroup>
```
