### ISSUE TITLE
Support for Microsoft.EntityFrameworkCore.InMemory?

### ISSUE THREAD

**Issue by saliksaly** [efcore/EFCore.SqlServer.HierarchyId#23]
Hi,

Is somehow possible to unit test app with entities using HierarchyId type properties?

I have added a prop of HierarchyId  type to one my entitties, running project and I got error:
System.InvalidOperationException : No suitable constructor found for entity type 'HierarchyId'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'value' in 'HierarchyId(SqlHierarchyId value)'.

I have tried to use .UseHierarchyId() with memory database configuration but the method is supposed only for SqlServerDbContextOptionsBuilder, as expected.

Similar to this issue: https://github.com/bricelam/EFCore.SqlServer.HierarchyId/issues/2

Project to demonstrate this issuse: https://github.com/saliksaly/aspnetcoreapp-efcore-inmemory-EFCore.SqlServer.HierarchyId
Just get and run.

Thanks for your help...

**Comment by bricelam** [comment]
This may be fixed in EF Core 5.0. I seem to remember some work in this area. I'll try it and see.

**Comment by bricelam** [comment]
Oh wait, we need to implement a value comparer. There are probably bugs around change tracking even in SQL Server because we don't.

**Comment by bricelam** [comment]
I take it back, we don't have bugs in change tracking because HierarchyId is immutable.

**Comment by kmataru** [comment]
Actually, the EF Core InMemory uses different service interfaces.

I made a local version that is working and I was thinking to make a PR for that, but considering it targets the InMemory, then I was thinking it would be more suited to have a new repository or at least NuGet package for that: `EFCore.InMemory.HierarchyId`.

**Comment by Cododoc** [comment]
Hello! Is there any progress for this issue?

**Comment by kmataru** [comment]
There is working solution for this, but it requires some unit tests: #33

**Comment by kmataru** [comment]
Finished with the PR, it just requires approval.

**Comment by bricelam** [comment]
Resolved by PR #33
