### ISSUE TITLE
GetDescendant returns an invalid HierarchyId string exception

### ISSUE THREAD

**Issue by AndyBates6668** [efcore/EFCore.SqlServer.HierarchyId#30]
The following code raises an exception:

            var first = HierarchyId.Parse("/0/");
            var second = HierarchyId.Parse("/1/");
            var parent = first.GetAncestor(1);

            var newNode = parent.GetDescendant(first, second);

I've tested this in SQL and it returns the correct value of /0.1/ where the component appears to return //0.1/.

**Comment by ErikEJ** [comment]
@dotmorten ?

**Comment by AndyBates6668** [comment]
I've raised the issue against dotMorten.SqlHierarchy.Types so closing the incident here.
