### ISSUE TITLE
Build Error Using 2.1.0 - "uses 'Microsoft.EntityFrameworkCore.SqlServer, Version=42.42.42.42..."

### ISSUE THREAD

**Issue by dfaivre** [efcore/EFCore.SqlServer.HierarchyId#39]
Getting a build time error when using v2.1.0. I don't get it with 2.0.0.

Reproduction code here: https://github.com/dfaivre/bugrepro__efcore_hierarchy_id__2-1-0

Thanks for the great project!

**Comment by bricelam** [comment]
Doh. I had a local build of EF Core 5.0.1 in my NuGet cache. 🤦‍♂️

**Comment by dfaivre** [comment]
Thank you!
