### ISSUE TITLE
Reverse engineer support

### ISSUE THREAD

**Issue by bricelam** [efcore/EFCore.SqlServer.HierarchyId#5]
- [ ] Add [some build targets](https://github.com/dotnet/efcore/blob/master/src/EFCore.SqlServer.NTS/build/netstandard2.1/Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite.targets)
- [ ] Add [the design-time services](https://github.com/dotnet/efcore/blob/master/src/EFCore.SqlServer.NTS/Design/Internal/SqlServerNetTopologySuiteDesignTimeServices.cs)

**Comment by cutig3r** [comment]
This may be addressed, by #14

**Comment by bricelam** [comment]
Yep. That should do it.

**Comment by bricelam** [comment]
Fixed by #14
