### ISSUE TITLE
Question: Does this package support reverse engineering?

### ISSUE THREAD

**Issue by ErikEJ** [efcore/EFCore.SqlServer.HierarchyId#52]

**Comment by bricelam** [comment]
I think so (issue https://github.com/efcore/EFCore.SqlServer.HierarchyId/issues/5).

Like NTS, you'll need to add [the design-time services](https://github.com/efcore/EFCore.SqlServer.HierarchyId/blob/master/EFCore.SqlServer.HierarchyId/Design/SqlServerHierarchyIdDesignTimeServices.cs) if your reverse-engineering programatically.

**Comment by ErikEJ** [comment]
Thanks!
