### ISSUE TITLE
Not support dapper

### ISSUE THREAD

**Issue by Zero-Xiong** [efcore/EFCore.SqlServer.HierarchyId#57]
```cs
using Dapper;
using Microsoft.EntityFrameworkCore;

var sql = $" select * from tableA where columnA = '{columnA}'";
using (IDbConnection db = new SqlConnection(......))
{
    var result = await db.QueryAsync<EntityA>(sql);
    return result.ToList();
}

class EntityA
{
    public HierarchyId columnA {get;set;}
}
```

will get the error:

![image](https://user-images.githubusercontent.com/13866194/118919363-f13c5d80-b966-11eb-86a1-b50e7a5789b2.png)

**Comment by bricelam** [comment]
@Zero-Xiong You shouldn't need this project to use `hierarhcyid` on Dapper. You should just be able to use [dotmorten.Microsoft.SqlServer.Types](https://www.nuget.org/packages/dotmorten.Microsoft.SqlServer.Types) directly.

```cs
using Dapper;
using Microsoft.SqlServer.Types;

var sql = $" select * from tableA where columnA = '{columnA}'";
using (IDbConnection db = new SqlConnection(......))
{
    var result = await db.QueryAsync<EntityA>(sql);
    return result.ToList();
}

class EntityA
{
    public SqlHierarchyId columnA {get;set;}
}
```

**Comment by Zero-Xiong** [comment]
@bricelam Thanks!

I found one solution:

`internal class HierarchyIdTypeHandler : SqlMapper.ITypeHandler
    {
        public object Parse(Type destinationType, object value)
        {
            return HierarchyId.Parse(value?.ToString());
        }

        public void SetValue(IDbDataParameter parameter, object value)
        {
            parameter.Value = value?.ToString();
        }
    }`


and then register the TypeHandler for SqlMapper


` Dapper.SqlMapper.AddTypeHandlerImpl(typeof(HierarchyId), new HierarchyIdTypeHandler(), false);`

finally it works

**Comment by bricelam** [comment]
FYI, the `value` parameter in `HierarchyIdTypeHandler.Parse()` is a `SqlHierarchyId`. You could avoid `HierarchyId` entirely if you wanted.

Also, because you're sending nvarchar parameters, queries like this won't work:

```sql
select * from tableA where @p.IsDescendantOf(columnA)
```
