### ISSUE TITLE
Issues with specific values

### ISSUE THREAD

**Issue by Jabe** [efcore/EFCore.SqlServer.HierarchyId#7]
There is an issue with specific values. Using the following code in linqpad:

```c#
var parsed = HierarchyId.Parse("/1.3.2/").Dump("parsed");
var ms = new MemoryStream();
parsed.Write(new BinaryWriter(ms));
ms.Position = 0;
var roundTrip = HierarchyId.Read(new BinaryReader(ms)).Dump("roundTrip");
```

|Input|Value of parsed|Value of roundTrip|
|-----|-----|-----|
|/1.0.2/|/1.0.2/|/1.0.2/|
|/1.1.2/|/1.1.2/|/1.1.2/|
|/1.2.2/|/1.2.2/|/1.2.2/|
|/1.3.2/|/1.3.2/|InvalidCastException: No pattern found for: 11010|
|/3.0/|/3.0/|/|

Using `Microsoft.SqlServer.Types.SqlHierarchyId (Microsoft.SqlServer.Types, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null)` directly in netcore31 (linqpad6) produces the same bad result.

Using `Microsoft.SqlServer.Types.SqlHierarchyId (Microsoft.SqlServer.Types, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91)` directly in net46+ (linqpad5) works with all tested values as expected.

**Comment by bricelam** [comment]
Likely an issue with [dotMorten/Microsoft.SqlServer.Types](https://github.com/dotMorten/Microsoft.SqlServer.Types).

**Comment by Jabe** [comment]
Indeed, thanks. Didn't realize there's a dependency. I've created a [new issue](https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/35) over at dotMorten.
