### ISSUE TITLE
SqlServerHierarchyIdTypeMappingSourcePlugin.FindMapping returns wrong type mapping when mappingInfo.ClrType is null

### ISSUE THREAD

**Issue by yuryjhol** [efcore/EFCore.SqlServer.HierarchyId#72]
fix:
public virtual RelationalTypeMapping FindMapping(in RelationalTypeMappingInfo mappingInfo)
        {
            var clrType = mappingInfo.ClrType/* ?? typeof(HierarchyId)*/;
            var storeTypeName = mappingInfo.StoreTypeName;

            return typeof(HierarchyId).IsAssignableFrom(clrType) || storeTypeName == SqlServerTypeName
                ? new SqlServerHierarchyIdTypeMapping(SqlServerTypeName, clrType ?? typeof(HierarchyId))
                : null;
        }
See how the same logic realized in SqlServerNetTopologySuiteTypeMappingSourcePlugin.

**Comment by bricelam** [comment]
What is the functional impact of this bug? What user scenario fails because of it?
