### ISSUE TITLE
Navigation property support

### ISSUE THREAD

**Issue by binaryevents** [efcore/EFCore.SqlServer.HierarchyId#8]
Hi,
Thanks for all your work.

Do you know a possibility to get navigation properties to work with HirachyId?
``` cs
    class Patriarch
    {
        public HierarchyId Id { get; set; }
        public string Name { get; set; }
        public Patriarch Father{ get; set; }
    }
``` 
with
``` cs
modelBuilder.Entity<Patriach>()
                .HasOne(x => x.Father)
                .WithMany()
                .HasForeignKey(x => x.Id.GetAncestor(1));
```
complains about the property expression.

`The properties expression 'x => x.Id.GetAncestor(1)' is not valid. The expression should represent a simple property access: 't => t.MyProperty'. When specifying multiple properties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'.`

due to my limited knowledge about the ef core internals, I was not able to work out a solution on my own.

Thanks,
Robert

**Comment by bricelam** [comment]
Hmm, that would require a new feature in EF Core. Today, I think the best you can do is to add another HierarchyId column with a CHECK constraint.

```cs
modelBuilder.Entity<Patriach>()
    .HasCheckConstraint(
        "CK_Patriarch_FatherId",
        "FatherId = Id.GetAncestor(1)");
```
