### ISSUE TITLE
Support for EFCore 6.0

### ISSUE THREAD

**Issue by an-hb** [efcore/EFCore.SqlServer.HierarchyId#83]
Hi,

I'm interested in using HierarchyId with EFCore/.NET 6 and was wondering if/when you plan to release version 3.0.0.

Best regards

**Comment by cwe1ss** [comment]
I also just tried updating our project to the final 6.0.0 bits and I received this error:
```
{"Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EntityFrameworkCore.SqlServer.HierarchyId, Version=2.1.0.0, Culture=neutral, PublicKeyToken=0c30ba8633cb7b1e' does not have an implementation.":"ExtensionInfo"}
```

IIUC, the pending PR #74 will fix this.

Let us know if there's anything we can help with here. 

Thank you for this project!

**Comment by bricelam** [comment]
Fear not! I'm going to release an updated package today.

**Comment by cwe1ss** [comment]
Not all heroes wear capes! 😀 thank you!

**Comment by bricelam** [comment]
Published.
